Repository this-is-MERGE/Backend, pull requests merged in 2023-11, with the labels that each got.

#1 Feature login
  src/controller/UserController.js
  src/index.js
  src/model/User.js
  src/routes/routes.js
Labels: feature

#2 Feature patient
  src/controller/PatientController.js
  src/controller/UserController.js
  src/index.js
  src/model/Patient.js
  src/model/User.js
  src/routes/routes.js
Labels: feature, fix, Refactor

#3 Feature patient
  src/controller/PatientController.js
  src/controller/UserController.js
  src/model/Patient.js
Labels: feature, Refactor

#5 Feature patient
  src/controller/PatientController.js
  src/model/Patient.js
Labels: fix, Refactor

#6 Feature patient
  src/controller/PatientController.js
  src/model/Patient.js
  src/routes/routes.js
Labels: Refactor
